Repository bcgov/climr, pull requests merged in 2024-02, with the labels that each got.

#200 add plot_bivariate() function
  .github/workflows/R-CMD-check.yaml
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/globalVars.R
  R/plot_bivariate.R
  man/plot_bivariate.Rd
Labels: enhancement

#209 189 `list_historic()` does not provide accurate information for `climr_downscale(..., historic_ts)`
  .github/workflows/pkgdown.yaml
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/append_clim_vars.R
  R/cache.R
  R/calc_DD.R
  R/calc_Eref_CMD.R
  R/climr-package.R
  R/climr_downscale.R
  R/data-lists.R
  R/dbGetRaster.R
  R/downscale.R
  R/example_data.R
  R/gcm.R
  R/globalVars.R
  R/helper-testInit.R
  R/historic.R
  R/lapserate.R
  R/normal.R
  R/plot_bivariate.R
  R/utils.R
  data-raw/derivedVariables/functions.R
  data-raw/example_data.R
  data-raw/internal_data.R
  man/climr_downscale.Rd
  man/data-option-lists.Rd
  man/downscale.Rd
  man/gcm-input-data.Rd
  man/hist-input-data.Rd
  man/plot_bivariate.Rd
  tests/testthat/reference_outputs.R
  tests/testthat/setup.R
  tests/testthat/test-cache.R
  tests/testthat/test-calcfuns.R
  tests/testthat/test-climr_downscale.R
  tests/testthat/test-downscale.R
  tests/testthat/test-gcm_input.R
  tests/testthat/test-get_bb.R
  tests/testthat/test-historic_input.R
  tests/testthat/test-lapserate.R
  tests/testthat/test-normal_input.R
  vignettes/climr_with_rasters.Rmd
  vignettes/climr_workflow_beg.Rmd
  vignettes/climr_workflow_int.Rmd
  vignettes/methods_downscaling.Rmd
Labels: enhancement, v1.0.0

#212 Miscellaneous edits to documentation and vignettes
  DESCRIPTION
  R/downscale.R
  R/gcm.R
  R/plot_bivariate.R
  README.md
  vignettes/climr_workflow_beg.Rmd
Labels: documentation

#210 142 use `...` to pass arguments to inner functions
  DESCRIPTION
  NEWS.md
  R/climr_downscale.R
  R/downscale.R
  man-roxygen/out_spatial.R
  man-roxygen/plot.R
  man-roxygen/return_normal.R
  man-roxygen/vars.R
  man/climr_downscale.Rd
  man/downscale.Rd
  man/plot_bivariate.Rd
  vignettes/climr_with_rasters.Rmd
Labels: enhancement, v1.0.0
